version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    labels:
      - dependencies
      - github-actions
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 5
    automerge: true

  # Python uv
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    labels:
      - dependencies
      - python

  # Docker
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    labels:
      - dependencies
      - docker
    automerge: true
    allow:
      - dependency-type: "all"
        update-types: [ "version-update:semver-minor", "version-update:semver-patch" ]

  # Docker Compose
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    labels:
      - dependencies
      - docker-compose
    automerge: true
    allow:
      - dependency-type: "all"
        update-types: [ "version-update:semver-minor", "version-update:semver-patch" ]
