stages:
  - "test"

.test-template:
  stage: test
  image: python:3.13.5-slim-bullseye
  tags:
    - kubernetes-runner
    - docker-runner
  except:
    - tags
  before_script:
    - apt update && apt install -y git
    - pip install uv
    - uv sync --locked

ruff:
  extends:
    - .test-template
  script:
    - pre-commit run ruff -a
