stages:
  - "test"

.test-template:
  stage: test
  image: python:3.11.4-slim-bullseye
  tags:
    - kubernetes-runner
    - docker-runner
  except:
    - tags
  before_script:
    - apt update && apt install -y git
    - pip install poetry==1.8.2
    - poetry config virtualenvs.create false
    - poetry install

ruff:
  extends:
    - .test-template
  script:
    - pre-commit run ruff -a
