name: "🐞 Bug Report"
description: "Report an issue to help the project improve."
title: "[Bug] "
labels: [Bug]

body:
  - type: markdown
    attributes:
      value: |
        # 🐞 Bug Report
        Please fill out the form below to help us understand and fix the problem faster.
        > 💡 **Tip:** Search existing issues before creating a new one.

  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Explain what went wrong..."
    validations:
      required: true

  - type: dropdown
    id: regression
    attributes:
      label: "Is this a regression?"
      description: "Did this behaviour work in a previous version?"
      options:
        - "Yes"
        - "No"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to reproduce"
      description: "Provide the exact steps to reproduce the problem."
      placeholder: |
        1. Use x argument / navigate to ...
        2. Fill in this information...
        3. Go to...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behaviour"
      description: "What did you expect to happen?"
      placeholder: "Describe what you expected to happen..."
    validations:
      required: true

  - type: textarea
    id: media
    attributes:
      label: "Media proof"
      description: "If applicable, add screenshots or videos."
      placeholder: "Attach links or drag & drop files here."

  - type: input
    id: os
    attributes:
      label: "Operating System"
      placeholder: "e.g., Ubuntu 20.04, Windows 10"

  - type: input
    id: node
    attributes:
      label: "Python version"
      placeholder: "e.g., Python 3.15.5"

  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Any other context or additional information."
