name: "📚 Documentation or README.md issue report"
description: "Report an issue in the project's documentation or README.md file."
title: "[Docs] "
labels: [Documentation]
body:
  - type: markdown
    attributes:
      value: |
        ## 📚 Documentation Issue Report

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the documentation bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the issue.
        Example:
        1. Go to page...
        2. Click on...
        3. See error
      placeholder: |
        1.
        2.
        3.
        4.

  - type: textarea
    id: media
    attributes:
      label: Media proof
      description: If applicable, add screenshots or videos to help explain your problem.

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or additional information about the problem here.
