name: "🚀🆕 Feature Request"
description: "Suggest an idea or possible new feature for this project."
title: "[Feat] "
labels: [Feature]
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request

  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. For example — "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or additional information about the problem here.
